version: '3.8'

services:
  minio-console:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: minio-console
    ports:
      - "9090:9090"
      - "9443:9443"
    environment:
      # Required: MinIO Server endpoint
      CONSOLE_MINIO_SERVER: "${CONSOLE_MINIO_SERVER:-http://minio:9000}"

      # Optional: If not set, random values will be generated on startup
      # WARNING: Sessions will be lost on container restart without these!
      # Generate secure values with: openssl rand -base64 32
      CONSOLE_PBKDF_PASSPHRASE: "${CONSOLE_PBKDF_PASSPHRASE:-}"
      CONSOLE_PBKDF_SALT: "${CONSOLE_PBKDF_SALT:-}"

      # Optional: Port configuration
      CONSOLE_PORT: "9090"

      # Optional: Debug logging (0-6, default 0)
      # CONSOLE_DEBUG_LOGLEVEL: "0"

      # Optional: TLS configuration
      # CONSOLE_TLS_PORT: "9443"
      # CONSOLE_TLS_CERTIFICATE: "/certs/public.crt"
      # CONSOLE_TLS_KEY: "/certs/private.key"

    # Uncomment to mount TLS certificates
    # volumes:
    #   - ./certs:/home/console/.console/certs:ro

    # Uncomment if running with a local MinIO server
    # depends_on:
    #   - minio

    networks:
      - minio-network

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Optional: MinIO server for testing
  # Uncomment this section if you want to run MinIO alongside the console
  # minio:
  #   image: quay.io/minio/minio:latest
  #   container_name: minio
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     MINIO_ROOT_USER: minioadmin
  #     MINIO_ROOT_PASSWORD: minioadmin
  #   command: server /data --console-address ":9001"
  #   volumes:
  #     - minio-data:/data
  #   networks:
  #     - minio-network
  #   healthcheck:
  #     test: ["CMD", "mc", "ready", "local"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

networks:
  minio-network:
    driver: bridge

# volumes:
#   minio-data:
